config/routes.rb
Rails.application.routes.draw do
  resources :slack_webhooks, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  get '/', to: 'player#welcome'
  get 'test', to: 'player#test'
  get 'player', to: 'player#show', as: :player

  # config/routes.rb
  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cable.rb
class Cable
  def self.broadcast(channel, payload={})
    ActionCable.server.broadcast channel, payload
  end
end

app/models/dj.rb
class DJ
  class PlaylistAlreadyEndedError < StandardError; end

  attr_reader :player, :playlist, :user_rota

  def initialize(player, playlist, user_rota)
    @player = player
    @playlist = playlist
    @user_rota = user_rota
  end

  # TODO - use whisper and listen for an event
  def new_video_added!
    start! if waiting?
  end

  def waiting?
    player.stopped? and playlist.any_unplayed?
  end

  def finished?
    player.stopped? and playlist.all_played?
  end

  def playing?
    player.playing?
  end

  def current_video
    player.video
  end

  def start!
    if playlist.any_unplayed?
      player.play!(video_selector.start)
    else
      raise PlaylistAlreadyEndedError, "Playlist #{playlist.id} already ended"
    end
  end

  def stop!
    player.stop!
  end

  def switch!
    if playlist.any_unplayed?
      player.switch!(video_selector.next)
    else
      stop!
    end
  end

  private

  def video_selector
    @video_selector ||= VideoSelector.new(playlist, user_rota)
  end
end

app/models/player.rb
class Player < ApplicationRecord

  class PlayerAlreadyPlayingError < StandardError; end
  class PlayerAlreadyStoppedError < StandardError; end

  STATUSES = ['stopped', 'playing']

  validates :status, inclusion: { in: STATUSES }

  belongs_to :video, optional: true

  def eject_video
    update_attributes(video_id: nil)
  end

  def stopped?
    status == "stopped"
  end

  def set_video(video)
    update_attributes(video_id: video.id) and video.played!
  end

  def playing?
    status == "playing"
  end

  def play!(video)
    Player.transaction do
      if stopped? and set_video(video) and update_attribute(:status, "playing")
        Cable.broadcast 'player_channel', nextVideoId: video.youtube_id
        true
      else
        raise PlayerAlreadyPlayingError, "Player #{self.id} is already playing video id:#{video_id}."
      end
    end
  end

  def stop!
    Player.transaction do
      if playing? and eject_video and update_attribute(:status, "stopped")
        Cable.broadcast 'player_channel', stop: true
        true
      else
        raise PlayerAlreadyStoppedError, "Player #{self.id} is already stopped."
      end
    end
  end

  def switch!(video)
    true if stop! and play!(video)
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord

  has_many :videos, dependent: :destroy
  belongs_to :team, optional: true

  def next_video
    videos.unplayed.oldest_first.limit(1).take
  end

  def add_video!(attr={})
    videos.create!(attr)
  end

  def any_unplayed?
    videos.unplayed.any?
  end

  def all_played?
    videos.unplayed.none?
  end

  def last_played(amount=20)
    videos.played.order(played_at: :desc).limit(amount)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :slack_id, presence: true
  has_many :users, -> { order("position ASC") }, dependent: :destroy
  has_one :player, dependent: :destroy
  has_one :playlist, dependent: :destroy

  def user_rota
    @user_rota ||= UserRota.new(self)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :videos
  belongs_to :team, optional: true
  acts_as_list scope: :team

  validates :slack_id, presence: true
end

app/models/user_rota.rb
class UserRota
  def initialize(team)
    @team = team
  end

  def advance_to_next_turn
    team.users.first.move_to_bottom
  end

  def current_user
    team.users.first
  end

  def all
    team.users
  end

  private

  attr_reader :team
end

app/models/video.rb
require 'cgi'

class Video < ApplicationRecord

  belongs_to :playlist, optional: true
  belongs_to :user, optional: true

  before_validation :set_youtube_id

  validates :user_id, :youtube_id, presence: true

  def self.oldest_first
    order("created_at ASC")
  end

  def self.next_for(user)
    unplayed.where(user_id: user.id).take
  end

  def self.unplayed
    where(played_at: nil)
  end

  def self.played
    where("played_at IS NOT NULL")
  end

  def played!
    self.update_attribute(:played_at, Time.current)
  end

  def played?
    played_at.present?
  end

  private

  def set_youtube_id
    return unless url.present?
    self.youtube_id = CGI.parse(URI.parse(url).query)["v"].first
  end
end

app/models/video_selector.rb
class VideoSelector
  def initialize(playlist, user_rota)
    @playlist = playlist
    @user_rota = user_rota
  end

  def next
    user_rota.advance_to_next_turn
    each_turns_next_video.first
  end

  def start
    each_turns_next_video.first
  end

  private

  attr_reader :playlist, :user_rota

  # TODO optimize with window function?
  def each_turns_next_video
    user_rota.all.map{ |user| Video.next_for(user) }.compact
  end
end

app/models/you_tube_url.rb
require 'uri'
require 'cgi'

class YouTubeUrl
  def initialize(url)
    @url = url
  end

  def to_s
    @url
  end

  def video_id
    @video_id ||= begin
      values = CGI::parse(uri.query)["v"]
      values.first if values.any?
    end
  end

  def uri
    @uri ||= URI.parse(@url)
  end

  def valid?
    (uri.scheme == "http" or "https") and (uri.host =~ /.*?youtube.com/) and video_id.length == 11
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController

  before_action :load_team, except: [:test, :welcome]

  def show
    @dj = DJ.new(player, playlist, team.user_rota)
    @dj.start! if @dj.waiting?
  end

  def test
    redirect_to root_path unless Rails.env.development?
  end

  def welcome
  end

  private

  def load_team
    @_team = Team.take!

  rescue ActiveRecord::RecordNotFound => e
    redirect_to '/'
  end

  def team
    @_team
  end

  def player
    @_player = team.player
  end

  def playlist
    @_playlist = team.playlist
  end
end

app/controllers/slack_webhooks_controller.rb
class SlackWebhooksController < ApplicationController

  skip_before_action :verify_authenticity_token, only: :create

  before_action :ensure_valid_command

  def create
    result = operation.call(create_params)
    if result.success?
      render text: result.message, status: :created
    else
      Rails.logger.error { "#{result.errors}" }
      render text: result.errors, status: :unprocessable_entity
    end
  end

  private

  def create_params
    {
      team: team,
      user: user,
      playlist: playlist,
      dj: dj,
      command: params['text']
    }
  end

  def team
    @_team ||= Team.find_or_create_by(slack_id: params['team_id'])
  end

  def player
    @_player ||= Player.find_or_create_by(team_id: team.id)
  end

  def user
    @_user ||= User.find_or_create_by(slack_id: params['user_id'], team_id: team.id) do |u|
      u.name = params['user_name']
    end
  end

  def playlist
    @_playlist ||= Playlist.find_or_create_by(team_id: team.id)
  end

  def dj
    @_dj ||= DJ.new(player, playlist, team.user_rota)
  end

  def operation
    @_operation = commands.detect {|c| c.match?(params['text']) }
  end

  def commands
    [
      PlayVideo,
      FindVideo,
      SkipVideo,
      ShowHelp,
      ShowHistory
    ]
  end

  def ensure_valid_command
    if operation.nil?
      Rails.logger.error { "slack webhook command not valid: #{params[:text]} for team #{params[:team_id]} and user #{params[:user_id]}" }
      head :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/slack_webhooks_helper.rb
module SlackWebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slackdj</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/show.html.erb
<div class="container">
  <% if @dj.finished? %>
    <div class="alert alert--notice">
      <h1>Welcome to SlackDJ</h1>
      <p>Currently there are no videos to play.</p>
      <p>To add a video type in Slack <em>/dj find michael jackson thriller</em></p>
      <p>Then reload this page to start playing.</p>
      <p>For more options type <em>/dj help</em></p>
    </div>
  <% end %>

  <div class="player-wrapper">
    <div id="player"></div>
  </div>
</div>

<script type="text/javascript">
  player = {
    play: function(videoId){
      if (_.isNil(this._player)) {
        this._player = this.initializePlayer(videoId);
      } else {
        this._player.loadVideoById({videoId: videoId});
      }
    },

    stop: function(){
      this._player.stopVideo();
    },

    initializePlayer: function(videoId){
       return new YT.Player('player', {
          height: '390',
          width: '640',
          videoId: videoId,
          playerVars: {
            controls: '<%= Rails.env.development? ? 1 : 0 %>'
          },
          events: {
            'onReady': this.onPlayerReady,
            'onStateChange': this.onPlayerStateChange
          }
       });
    },

    onPlayerReady: function(event) {
      event.target.playVideo();
    },

    onPlayerStateChange: function(event) {
      if (event.data == YT.PlayerState.ENDED) {
        // TODO emit event and have channel listen for it?
        window.App.player.next(player._player.getVideoData().video_id);
      }
    }
  };


  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  var videoId;

  <% if @dj.playing? %>
    videoId = '<%= @dj.current_video.youtube_id %>';
  <% end %>


  function onYouTubeIframeAPIReady() {
    if (!_.isNil(videoId)){
      console.log("frame ready", videoId);
      player.play(videoId);
    }
  }
</script>

app/views/player/test.html.erb
<%= form_tag slack_webhooks_path, remote: true do %>

  <label>User id
    <%= text_field_tag :user_id, 1 %>
  </label>

  <label>Team id
    <%= text_field_tag :team_id, 1 %>
  </label>
  <fieldset>
    <legend>Play...</legend>
    <label>
      <%= radio_button_tag :text, 'play https://www.youtube.com/watch?v=mmi60Bd4jSs' %>
      Daft Punk Da Funk
    </label>

    <label>
      <%= radio_button_tag :text, 'play https://www.youtube.com/watch?v=UclCCFNG9q4' %>
      Gorillaz Clint Eastwood
    </label>

    <label>
      <%= radio_button_tag :text, 'play https://www.youtube.com/watch?v=pbTNZN6m0HM' %>
      Moloko Sing It Back
    </label>

  </fieldset>


  <fieldset>
    <legend>Find...</legend>
    <label>
      <%= radio_button_tag :text, 'find michael jackson thriller' %>
      MJ Thriller
    </label>

    <label>
      <%= radio_button_tag :text, 'find moby go' %>
      Moby Go
    </label>

    <label>
      <%= radio_button_tag :text, 'find deelite groove is in the heart' %>
      Deelite Groove Is In The Heart
    </label>

  </fieldset>

  <fieldset>
    <legend>Skip</legend>
    <%= radio_button_tag :text, 'skip' %>
  </fieldset>

  <fieldset>
    <legend>Help</legend>
    <%= radio_button_tag :text, 'help' %>
  </fieldset>

  <fieldset>
    <legend>History</legend>
    <%= radio_button_tag :text, 'history' %>
  </fieldset>
  <%= submit_tag 'post' %>
<% end %>

app/views/player/welcome.html.erb
<div class="container">
  <div class="alert alert-info">
    <h1>How to get started</h1>

    <p>To start playing videos you need to:</p>

    <ul>
      <li>Setup the custom DJ command in your slack account.</li>
      <li>Add your first song via the Slack app.</li>
      <li>Visit the <%= link_to "player", player_path %> to start watching.</li>
    </ul>

    <p>
      To add videos in Slack simply type:<br>
      <em>/dj find artist and song name</em><br>
      <em>/dj find michael jackson thriller</em>
    </p>

    <p>
      Learn more commands by typing:
      <em>/dj help</em>
    </p>
  </div>
</div>

app/views/slack_webhooks/create.html.erb
<h1>SlackWebhooks#create</h1>
<p>Find me in app/views/slack_webhooks/create.html.erb</p>